.TH envs 1 "06 September 2019" "v0.0.4"
.SH NAME
envs \- wrapper for user-submitted scripts and users_info.json entrys
supports user settings, submission and admin approval
.SH SYNOPSIS
.B envs [options] (scriptname)
.P
.SH DESRIPTION
.B envs
is a wrapper around user-submitted scripts.
any accepted script in /envs/bin can be run with
the wrapper feature.

users can submit any script in their ~/bin directory
which will be mailed to admins for review.

users can also manage youre `users_info.json` entrys from the `~/.envs`-file.
.SH USAGE
.TP
.B envs list
List all available scripts in /envs/bin
.TP
.B envs [scriptname]
Run scriptname.
.TP
.B envs submit
Submit a script from your ~/bin directory
.TP
.B envs about [scriptname]
Get the submitter's description for a script.
.TP
.B envs show
show your config file
.TP
.B envs edit
edit your config file
.TP
.B envs get <entry>
show a entry from your config
.TP
.B envs set <entry> <'value'>
set a entry to your config
.TP
.B envs unset <entry>
unset a entry from your config
.TP
.SH DEPENDENCIES
None.
.SH BUGS
None known. Please submit to https://git.envs.net/envs/envs_launcher/issues
.SH AUTHOR
Ben Harris <ben (at) tilde (dot) team>

Sven Kinne <creme (at) envs (dot) net>
