.TH tilde 1 "06 September 2019" "v0.0.4"
.SH NAME
tilde \- wrapper for user-submitted scripts and users_info.json entrys
supports user settings, submission and admin approval
.SH SYNOPSIS
.B tilde [options] (scriptname)
.P
.SH DESRIPTION
.B tilde
is a wrapper around user-submitted scripts.
any accepted script in /tilde/bin can be run with
the wrapper feature.

users can submit any script in their ~/bin directory
which will be mailed to admins for review.

users can also manage your `users_info.json` entries from the `~/.tilde`-file.
.SH USAGE
.TP
.B tilde list
List all available scripts in /tilde/bin
.TP
.B tilde [scriptname]
Run scriptname.
.TP
.B tilde submit
Submit a script from your ~/bin directory
.TP
.B tilde about [scriptname]
Get the submitter's description for a script.
.TP
.B tilde show
show your config file
.TP
.B tilde edit
edit your config file
.TP
.B tilde get <entry>
show a entry from your config
.TP
.B tilde set <entry> <'value'>
set a entry to your config
.TP
.B tilde unset <entry>
unset a entry from your config
.SH DEPENDENCIES
None.
.SH BUGS
None known. Please submit to https://github.com/tildeclub/launcher
.SH AUTHOR
Ben Harris <ben (at) tilde (dot) team>

Sven Kinne <creme (at) envs (dot) net>
