.TH TILDE 1 "August 2023" "Tilde User Scripts" "User Commands"

.SH NAME
tilde \- manage user-submitted scripts and apps

.SH SYNOPSIS
.B tilde
[\fIOPTION\fR] [\fICOMMAND\fR]

.SH DESCRIPTION
The \fBtilde\fR command is a script management tool for managing user-submitted scripts and apps on the system. It allows users to submit their scripts for approval by administrators, who can then approve or revoke them for system-wide usage.

By default, approved scripts are stored in the directory /tilde/bin, and their descriptions are kept in /tilde/descriptions.

.SH OPTIONS
.TP
.B \-h, \-\-help
Show usage information and exit.

.TP
.B \-v, \-\-version
Show version information and exit.

.SH COMMANDS
The following commands are supported:

.TP
.B list
Show a list of approved user scripts along with their descriptions.

.TP
.B submit
Start the submission flow for your own script. The script should be placed in the ~/bin directory, be executable, and respond to help or --help.

.TP
.B about \fIscript\fR
Show the description and details of a specific script.

.TP
.B approve
Enter the approval queue for pending scripts. This command is only accessible to the root user. Administrators can review pending submissions and approve them for system-wide usage.

.TP
.B revoke \fIscript\fR
Revoke a previously approved script. This command is only accessible to the root user.

.TP
.B run \fIscript\fR
Run an approved script by specifying its name. The script must be available in the /tilde/bin directory.

.SH PATH CONFIGURATION
To use approved scripts without invoking the \fBtilde\fR command, you can add /tilde/bin to your PATH environment variable. By doing so, the scripts in /tilde/bin will be accessible directly from the command line.

You can add /tilde/bin to your PATH by adding the following line to your shell configuration file (e.g., .bashrc or .zshrc):

.BP
\fBexport PATH=\$PATH:/tilde/bin\fR

Then, restart your shell or run the following command to apply the changes:

.BP
\fBsource ~/.bashrc\fR (or \fBsource ~/.zshrc\fR for Zsh)

.SH SEE ALSO
The \fBtilde\fR command is part of the tilde-scripts package. More information about the tilde-scripts package can be found on the tilde.team website.

.SH AUTHOR
\fBBen Harris\fR <\fBben@tilde.team\fR>

.SH COPYRIGHT
Copyright (C) 2018 Ben Harris.

.SH LICENSE
This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License at <http://www.gnu.org/licenses/> for more details.
